version: 0.2

phases:
  install:
    commands:
      - cd aws-cicd-flask-demo 
      - pip install -r requirements.txt

  build:
    commands:
      #Update build step to use `python -m py_compile` for syntax checking instead of starting the Flask server during CI
      - python -m py_compile app.py

artifacts:
  files:
    - '**/*'
